# authendication credintials
credentials:
  usernames:
    kalim:
      email: samannaisrat@gmail.com
      name: Samanna Israt
      password: $2b$12$Vya.5Gw0ur0pDxsjt22/suzsNMS/xXYti30GXZZFQ62nUWwmcLJFm # Placeholder for hashed password of 'abc'

cookie:
  expiry_days: 1
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - c191278@ugrad.iiuc.ac.bd



db:
  host: "localhost"
  user: "root"
  passwd: "@&&67&&@+7"
  database: "ExpenseDB"
  auth_plugin: "mysql_native_password"

  
email_sender:
  email: "israt@gmail.com"
  pass: '@&&@+7'